import { jsPDF } from 'jspdf';
import { ResearchSession } from '@/types';

export async function generateResearchPDF(session: ResearchSession): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add text with automatic page breaks
  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');

    const lines = doc.splitTextToSize(text, maxWidth);

    for (const line of lines) {
      if (yPosition + 10 > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    }
    yPosition += 5; // Add spacing after text block
  };

  // Header
  doc.setFillColor(41, 128, 185);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Deep Research Report', margin, 25);

  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // Research Info
  addText('Research Summary', 16, true);
  addText(`Initial Prompt: ${session.initialPrompt}`, 10);

  if (session.refinedPrompt) {
    addText(`Refined Prompt: ${session.refinedPrompt}`, 10);
  }

  addText(`Date: ${new Date(session.createdAt).toLocaleString()}`, 10);
  addText(`Status: ${session.status.toUpperCase()}`, 10);

  yPosition += 10;

  // Refinement Questions and Answers
  if (session.refinementQuestions.length > 0) {
    addText('Refinement Questions & Answers', 16, true);
    session.refinementQuestions.forEach((q, index) => {
      addText(`${index + 1}. ${q.question}`, 11, true);
      if (q.answer) {
        addText(`Answer: ${q.answer}`, 10);
      }
      yPosition += 3;
    });
  }

  yPosition += 10;

  // OpenAI Deep Research Results
  if (session.openaiResult) {
    addText('OpenAI Deep Research Results', 16, true);
    doc.setDrawColor(41, 128, 185);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 5;
    addText(session.openaiResult, 10);
    yPosition += 10;
  }

  // Gemini Research Results
  if (session.geminiResult) {
    addText('Google Gemini Research Results', 16, true);
    doc.setDrawColor(219, 68, 55);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 5;
    addText(session.geminiResult, 10);
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      `Generated by Multi-API Deep Research Assistant`,
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  }

  // Return PDF as buffer
  const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
  return pdfBuffer;
}
